# funcion input ()
var = input('SR usuario digine un mumero: ')
var = float(var)
print(var + 2)
numero = input("SR usuario digine un mumero: ")
numero = int(numero)
print(f'El numero que fue: {numero}')
var = float(input('SR usuario digine un mumero: '))
print(var + 2)
